export const sample_sweets = [
  {
    id: "1",
    name: "Dark Chocolate Truffle",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["france"],
    stars: 4.5,
    imageUrl: "sweet-1.jpg",
    tags: ["sweet", "dessert"],
  },
  {
    id: "2",
    name: "Milk Chocolate Bar",
    price: 20,
    cookTime: "5-10",
    favorite: true,
    origins: ["switzerland", "belgium"],
    stars: 5,
    imageUrl: "sweet-2.jpg",
    tags: ["sweet", "snack"],
  },
  {
    id: "3",
    name: "White Chocolate Raspberry",
    price: 15,
    favorite: false,
    origins: ["germany"],
    stars: 4.0,
    imageUrl: "sweet-3.jpg",
    tags: ["sweet", "dessert"],
  },
  {
    id: "4",
    name: "Chocolate Hazelnut Spread",
    price: 8,
    favorite: true,
    origins: ["italy"],
    stars: 4.8,
    imageUrl: "sweet-4.jpg",
    tags: ["spread", "breakfast"],
  },
  {
    id: "5",
    name: "Chocolate Mint Cookies",
    price: 12,
    favorite: false,
    origins: ["us", "uk"],
    stars: 4.3,
    imageUrl: "sweet-5.jpg",
    tags: ["sweet", "dessert", "snack"],
  },
  {
    id: "6",
    name: "Hot Chocolate",
    price: 5,
    favorite: false,
    origins: ["mexico", "south america"],
    stars: 4.5,
    imageUrl: "sweet-6.jpg",
    tags: ["beverage", "warm", "sweet"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "sweet", count: 5 },
  { name: "dessert", count: 3 },
  { name: "snack", count: 2 },
  { name: "spread", count: 1 },
  { name: "breakfast", count: 1 },
  { name: "beverage", count: 1 },
  { name: "warm", count: 1 },
];
